# Generated by Django 2.2.17 on 2021-03-31 11:11

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('runlaterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlater',
            name='survey',
            field=models.IntegerField(verbose_name=mainapp.models.Surveys),
        ),
    ]
