# Generated by Django 2.2.17 on 2021-03-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runlaterapp', '0002_auto_20210331_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlater',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Surveys'),
        ),
    ]
