# Generated by Django 2.2 on 2021-03-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='age',
            field=models.PositiveIntegerField(default=10, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
